<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="shree-PC" failures="1" tests="5" name="Car_Insurance" time="0.204" errors="0" timestamp="2022-01-20T18:08:16 IST">
  <testcase classname="testCase001.RetryTest" name="casetwo" time="0.016"/>
  <testcase classname="testCase001.RetryTest" name="retrylogictest" time="0.006">
    <skipped/>
  </testcase> <!-- retrylogictest -->
  <testcase classname="testCase001.RetryTest" name="retrylogictest" time="0.002">
    <skipped/>
  </testcase> <!-- retrylogictest -->
  <testcase classname="testCase001.RetryTest" name="retrylogictest" time="0.001">
    <skipped/>
  </testcase> <!-- retrylogictest -->
  <testcase classname="testCase001.RetryTest" name="retrylogictest" time="0.004">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at testCase001.RetryTest.retrylogictest(RetryTest.java:11)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- retrylogictest -->
</testsuite> <!-- Car_Insurance -->
